VIM

entrar en insert mode => i
salir del archivo => :q
guardar el archivo => :w
ir al inicio del archivo => gg
ir al final del archivo => G
ir al inicio o fin de un bloque => { }
se puede indicar la cantidad que se realizará el comando => numero (comando)
cortar una linea entera => dd
  - se pueden indicar más maneras de cuantas líneas se cortaran => d(comando)
deshacer los cambios => u
retrocer cuando se deshace el cambio => CTRL + R
copiar una linea => yy
pegar => p
entrar en insert mode agregando una nueva línea => o
entrar en visual mode => v
inicio de siguiente palabra => w
  - moverse al inicio de siguiente palabra después del próximo espacio en blanco => W
fin de siguiente palabra => e
  - moverse al fin de siguiente palabra después del próximo espacio en blanco => E
inicio de anterior palabra => b
  - moverse a la anterior palabra después del anterior espacio en blanco => B
moverse al inicio de la línea => 0
moverse al final de la línea => $
ir exactamente a la letra que se busca => f (letra)
ir un espacio anterior a la letra que se busca => t (letra)
  - ir a la siguiente coincidencia de la línea => ;
mover al inicio o fin de () [] {} => %
cambiar una cantidad => c (comando)
buscar la siguiente palabra igual => *
entrar en insert mode al final de la linea => A
eliminar la letra de la derecha => x
  - se puede indicar otro comando para indicar el límite de eliminación => x (comando)
cambiar el case de la letra => ~
  - indicar la cantidad letras que cambiará el case => (numero) ~
ejecutar el mismo comando anterior (period) => .
reemplazar la letra actual => r
  - indicar cuantas letras se cambiaran => (numero) r
cambiar toda la línea => R
entrar en modo modo visual seleccionando una línea => CTRL + V
entrar en modo modo visual seleccionando un bloque => SHIFT + V
identar para la derecha => >
indentar para la izquierda => <
crear macros para agrupar comandos => q (letra), llamar macro @(letra)
realizar un cambio a múltiples líneas => después de CTRL + V usar SHIFT + I y podremos agregar múltiples texto en todo el bloque seleccionado
